export const roadmapData = [
  {
    year: "2026 (Target)",
    title: "Ready for Full-Time Role",
    desc: "my goal is to start working full-time after completing training and building a professional portfolio.",
    details: [],
    current: false,
    future: true,
  },
  {
    year: "Nov 2025 - Dec 2025",
    title: "Digital Office Administration Training",
    desc: "Intensive training in Digital Office Administration (BBPVP). Improve administrative skills, document management, and mastery of digital applications.",
    details: [
      "Administration Digital Office",
      "Google Workspace & Microsoft Office",
      "Project-based learning 2 bulan",
    ],
    current: true,
    future: false,
  },
  {
    year: "Octo 2025 - Octo 2025",
    title: "Production Operator",
    desc: "PT SINAR MASKING LESTARI - Bekasi",
    details: [
      "Assembled product components",
      "Conducted quality checks",
      "Handled final packaging.",
    ],
    current: false,
    future: false,
  },
  {
    year: "Sept 2025 - Sept 2025",
    title: "Barista",
    desc: "Bliss Social Space - Bekasi",
    details: [
      "Prepared various coffee beverages",
      "Operated espresso machines and grinders",
      "maintained ingredient stock, cleaned equipment, handled cash transactions",
      "provided friendly customer service.",
    ],
    current: false,
    future: false,
  },
  {
    year: "Sept 2023 - Agst 2025",
    title: "Warehouse Staff",
    desc: "PT CHARGEURS PCC INDONESIA - KBN, Jakarta",
    details: [
      "Responsible for checking incoming and outgoing goods",
      "preparing outgoing items using the FIFO system",
      "receiving and arranging the placement of incoming goods",
      "performing routine stock takes to ensure inventory accuracy.",
    ],
    current: false,
    future: false,
  },
  {
    year: "June 2023 - July 2023",
    title: "Computer Store Staff",
    desc: "Virago Technicom - BCP mall, Bekasi",
    details: [
      "Provided customer service and handled sales transactions",
      "recorded stock availability and organized product displays",
      "prepared daily operational reports.",
    ],
    current: false,
    future: false,
  },
  {
    year: "Sept 2022 - Feb 2023",
    title: "Logistics Operator",
    desc: "PT TOYOTA MOTOR MANUFACTURING INDONESIA - Sunter, Jakarta",
    details: [
      "Managed supply chain and distribution processes",
      "checked and verified goods using hand scanner",
      "operated conveyor equipment to ensure smooth workflow",
    ],
    current: false,
    future: false,
  },
];
