export const roadmapData = [
  {
    year: "Nov 2025 - Dec 2025",
    title: "Digital Office Administration Training",
    desc: "Completed intensive Digital Office Administration training at BBPVP through project-based learning to strengthen administrative, documentation, and digital office skills.",
    details: [
      "Digital Office Administration",
      "Google Workspace & Microsoft Office",
      "Document Management & Reporting",
      "2-month Project-Based Learning",
    ],
    current: true,
    future: false,
  },
  {
    year: "Oct 2025",
    title: "Production Operator",
    desc: "PT Sinar Masking Lestari – Bekasi",
    details: [
      "Assembled product components following work instructions",
      "Performed quality checking to ensure product standards",
      "Handled final packaging with attention to detail",
    ],
    current: false,
    future: false,
  },
  {
    year: "Sept 2025",
    title: "Barista",
    desc: "Bliss Social Space – Bekasi",
    details: [
      "Prepared and served coffee beverages according to standards",
      "Managed ingredient stock and cleaned equipment",
      "Handled cash transactions and provided customer service",
    ],
    current: false,
    future: false,
  },
  {
    year: "Sept 2023 - Aug 2025",
    title: "Warehouse Staff",
    desc: "PT Chargeurs PCC Indonesia – KBN, Jakarta",
    details: [
      "Recorded incoming and outgoing goods data",
      "Prepared goods using FIFO system",
      "Arranged inventory placement and storage",
      "Performed routine stock opname to ensure data accuracy",
    ],
    current: false,
    future: false,
  },
  {
    year: "Jun 2023 - Jul 2023",
    title: "Computer Store Staff",
    desc: "Virago Technicom – BCP Mall, Bekasi",
    details: [
      "Provided customer service and handled sales transactions",
      "Recorded stock availability and organized product displays",
      "Prepared simple daily operational reports",
    ],
    current: false,
    future: false,
  },
  {
    year: "Aug 2022 - Feb 2023",
    title: "Logistics Operator",
    desc: "PT Toyota Motor Manufacturing Indonesia – Sunter, Jakarta",
    details: [
      "Supported supply chain and distribution processes",
      "Checked and verified goods using hand scanners",
      "Operated conveyor systems to ensure smooth logistics flow",
    ],
    current: false,
    future: false,
  },
];
